name: Vulnerable Workflow Test

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test-secrets-access:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Access Secret
        run: echo "Secret Value: ${{ secrets.fork }}"
